### ISSUE TITLE
Overlap with nugend/qspec ?

### ISSUE THREAD

**Issue by danielkrizian** [robmoore-i/qtest#1]
Hi Rob,

Have you had a look at https://github.com/nugend/qspec? It seems to offer the same features, according to the wiki: https://github.com/nugend/qspec/wiki

**Comment by robmoore-i** [comment]
Hi Daniel,

Thank you for showing this to me, I have been wondering about the existence of documented testing tools for Q after seeing KUnit and QUnit with relatively little documentation, this is great!

Many Thanks,

Rob
